config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, except: %i[index delete]
  delete 'post/delete', to: 'posts#destroy'

  get 'login', to: 'auth#show_login'
  post 'login', to: 'auth#login'
  post 'logout', to: 'auth#logout'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  get 'profile', to: 'users#profile'
  get 'profile/edit', to: 'users#edit', as: 'profile_edit'
  patch 'profile/update', to: 'users#update', as: 'profile_update'
  delete 'profile/delete', to: 'users#destroy'

  get 'password/edit', to: 'users#edit_password', as: 'password_edit'
  patch 'password/update', to: 'users#update_password', as: 'password_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  validates :title, presence: true, length: { maximum: 250 }
  validates :message, presence: true, length: { maximum: 2000 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  attr_accessor :current_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, on: :create
  validates :username, presence: true, length: { minimum: 4, maximum: 20 }
  validates :address, allow_blank: true, length: { maximum: 100 }
  validates :gender, presence: true
  validates :address, presence: true, length: { maximum: 100 }
  validate :current_password_is_correct, unless: proc { |user| user.current_password.nil? }

  def password_validation
    new_record? || password_digest_changed?
  end

  def current_password_is_correct
    errors.add(:current_password, 'is incorrect.') if User.find(id).authenticate(current_password) == false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    unless logged_in?
      flash[:alert] = 'Please Login'
      redirect_to login_path
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def show_login
    @user_auth = User.new
    render 'login'
  end

  def login
    @user_auth = UsersService.authenticate(params.permit(:email, :password))
    if @user_auth.errors.size.zero?
      session[:user_id] = @user_auth.id
      redirect_to root_path
    else
      render 'login'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_post, only: %i[show edit update destroy]
  before_action :check_public_post, only: %i[show edit]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    author_id = logged_in? ? current_user.id : nil
    @posts = PostsService.get_posts(author_id, params[:page], 15)
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post was created successfully.'
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was updated successfully.'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post with [id = #{@post.id}] was deleted"
    redirect_to root_path
  end

  private

  def fetch_post
    @post = PostsService.get_post(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :message, :is_public)
  end

  def check_public_post
    return if @post.is_public || @post.user == current_user

    flash[:alert] = 'You are not allowed to view this post'
    redirect_to root_path
  end

  def require_same_user
    return if current_user == @post.user

    flash[:alert] = 'You can only edit or delete your own article'
    redirect_to @post
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, only: %i[edit update edit_password update_password destroy]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :email, :password, :username, :gender, :address)
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'You have been registered successfully.'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def profile; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your Profile was updated successfully.'
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def edit_password; end

  def update_password
    password_params = params.require(:user).permit(:current_password, :password)
    if UsersService.update_password(@user, password_params).errors.empty?
      flash[:notice] = 'Password Updated.'
      redirect_to profile_path
    else
      render 'edit_password'
    end
  end

  def destroy
    @user.destroy
    flash[:alert] = 'Your Account has been deleted.'
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :gender, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_back_btn.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="pull-right">
      <%= link_to "Back", root_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/_confirm_delete.html.erb
<!-- Confirm delete Modal -->
<div class="modal fade" id="delete-confirm-modal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmPost" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteConfirmBoxTitle"><%= msg %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form_with(url: delete_path, local: true, method: :delete) do |f| %>
          <%= f.hidden_field :id, value: "id" %>
          <%= f.submit btn_txt, class: "btn btn-primary post-delete-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_msg.html.erb
<div aria-live="polite" aria-atomic="true" class="position-absolute top-0 end-0" style="min-height: 200px;">
  <% flash.each do |name, msg| %>
    <div class="toast text-white bg-<%= name == "notice" ? "success" : "danger" %> border-0 fade show" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
          <%= msg %>
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light">
  <div class="container justify-content-end">
    <% if logged_in? %>
      <% if current_user.is_admin? %>
      <span class="badge bg-primary">Admin</span>
      <% end %>
      <div class="dropdown">
        <a class="nav-link dropdown-toggle user-icon" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
          <i class="fas fa-user-circle fa-lg"></i>
          <span class="username"><%= current_user.username %></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', profile_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Log out', logout_path, class: "dropdown-item", method: :post %>
        </div>
      </div>
    <% else %>
      <div>
        <%= link_to 'Login', login_path, class: 'btn btn-outline-primary' %>
        <%= link_to 'Register', register_path, class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bulletin Board</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Klee+One:wght@400;600&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <div id="app">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="form-wrapper">
    <div class="form-group">
      <%= f.label :title, class: "control-label" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      <% if @post.errors[:title].present? %>
        <span class="form-text"><b><%= @post.errors[:title][0] %></b></span>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :message, class: "control-label" %>
      <%= f.text_area :message, class: "form-control", placeholder: "Message", size: '50x10' %>
      <% if @post.errors[:message].present? %>
        <span class="form-text"><b><%= @post.errors[:message][0] %></b></span>
      <% end %>
    </div>
    <div class="form-check">
      <%= f.check_box :is_public, class: "form-check-input", checked: true %>
      <%= f.label :is_public, 'Show on public?', class: "form-check-label" %>
    </div>
    <div class="col-md-12 text-center">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container main-content">
  <%= render 'layouts/back_btn' %>
  <div class="row content">
    <div class="col-md-6 mx-auto">
      <div class="card input-form">
        <div class="card-header text-center">Update News</div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "layouts/nav" %>

<div class="container main-content position-relative">
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <%= render 'layouts/flash_msg' %>
      <h2 class="float-start">Bulletin Board</h2>
      <div class="float-end">
        <%= link_to 'Add Post', new_post_path, class: 'btn btn-primary' %>
      </div>
    </div>

    <div class="col-lg-12">
      <div class="row posts-layout">
        <% @posts.each do |post| %>
          <div class="col-sm-6 col-lg-4 mb-4">
            <div class="card news-card <%= "not-public-news" unless post.is_public %>">
              <%= link_to post_path(post) do %>
                <div class="card-header">
                <span class="card-title">
                  <strong><%= post.title %></strong>
                </span>
                </div>
                <div class="card-body">
                  <p class="card-text"><%= truncate(post.message, length: 100) %></p>
                </div>
              <% end %>
              <div class="card-footer">
                <small class="text-muted"><%= time_ago_in_words(post.updated_at) %> ago</small>
                <span>
                  <% if logged_in? && post.user == current_user %>
                    <%= link_to edit_post_path(post), class: 'edit-btn' do %>
                      <i class="far fa-edit"></i>
                    <% end %>
                    <a href="#" class="delete-btn" data-id="<%= post.id %>" data-bs-toggle="modal" data-bs-target="#delete-confirm-modal">
                      <i class="far fa-trash-alt"></i>
                    </a>
                <% end %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <nav class="page-navigation">
        <%= will_paginate @posts, :container => false %>
      </nav>

      <%= render 'layouts/confirm_delete', msg: 'Please confirm this post will be delete.', delete_path: post_delete_path, btn_txt: 'Delete' %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container main-content">
  <%= render 'layouts/back_btn' %>
  <div class="row content">
    <div class="col-md-6 mx-auto">
      <div class="card input-form">
        <div class="card-header text-center">Create News</div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container main-content position-relative">
  <%= render 'layouts/back_btn' %>
  <div class="col-md-10 mx-auto align-middle content">
    <%= render 'layouts/flash_msg' %>
    <div class="card card-default">
      <div class="card-header text-center">
        <strong><%= @post.title %></strong>
      </div>
      <div class="card-body mx-auto">
        <p><%= @post.message %></p>
      </div>
      <div class="card-footer">
        <small><%= time_ago_in_words(@post.updated_at) %> ago</small>
        <% if logged_in? && @post.user == current_user %>
          <div class="float-right">
            <%= link_to edit_post_path(@post), class: 'edit-btn' do %>
              <i class="far fa-edit"></i>
            <% end %>
            <a href="#" class="delete-btn" data-id="<%= @post.id %>" data-bs-toggle="modal" data-bs-target="#delete-confirm-modal">
              <i class="far fa-trash-alt"></i>
            </a>
          </div>
        <% end %>
      </div>
    </div>
    <%= render 'layouts/confirm_delete', msg: 'Please confirm this post will be delete.', delete_path: post_delete_path, btn_txt: 'Delete' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container main-content">
  <%= render 'layouts/back_btn' %>
  <div class="col-lg-6 mx-auto content">
    <div class="card card-default input-form">
      <div class="card-header text-center">Edit Profile</div>
      <div class="card-body">
        <%= form_with(model: @user, url: profile_update_path, local: true, method: :patch) do |f| %>
          <div class="form-horizontal col-md-9 mx-auto user-form">
            <div class="form-group">
              <%= f.label :name, class: "control-label" %>
              <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
              <% if @user.errors[:name].present? %>
                <span class="form-text"><b><%= @user.errors[:name][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :email, class: "control-label" %>
              <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
              <% if @user.errors[:email].present? %>
                <span class="form-text"><b><%= @user.errors[:email][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :username, class: "control-label" %>
              <%= f.text_field :username, class: "form-control", placeholder: "UserName" %>
              <% if @user.errors[:username].present? %>
                <span class="form-text"><b><%= @user.errors[:username][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <div><%= f.label :gender, class: "control-label" %></div>
              <div class="form-check form-check-inline">
                <%= f.radio_button :gender, 'm', class: 'form-check-input' %>
                <%= f.label :gender, 'Male', class: "form-check-label", value: 'm' %>
              </div>
              <div class="form-check form-check-inline">
                <%= f.radio_button :gender, 'f', class: 'form-check-input' %>
                <%= f.label :gender, 'Female', class: "form-check-label", value: 'f' %>
              </div>
              <% if @user.errors[:gender].present? %>
                <span class="form-text"><b><%= @user.errors[:gender][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :address, class: "control-label" %>
              <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
              <% if @user.errors[:address].present? %>
                <span class="form-text"><b><%= @user.errors[:address][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<div class="container main-content">
  <%= render 'layouts/back_btn' %>
  <%= form_with(model: @user, url: password_update_path, local: true, method: :patch) do |f| %>
    <div class="row content">
      <div class="col-md-6 mx-auto">
        <div class="card input-form">
          <div class="card-header text-center">Change Password</div>
          <div class="card-body col-md-8 mx-auto user-form">
            <div class="form-group">
              <%= f.label :current_password, 'Current Password', class: "control-label" %>
              <%= f.password_field :current_password, class: "form-control", placeholder: "Enter Current Password" %>
              <% if @user.errors[:current_password].present? %>
                <span class="form-text"><b><%= @user.errors[:current_password][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :password, 'New Password', class: "control-label" %>
              <%= f.password_field :password, class: "form-control", placeholder: "Enter New Password" %>
              <% if @user.errors[:password].present? %>
                <span class="form-text"><b><%= @user.errors[:password][0] %></b></span>
              <% end %>
            </div>
            <div class="col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Update Password</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container main-content">
  <%= render 'layouts/back_btn' %>
  <div class="row">
    <div class="col-lg-6 mx-auto content">
      <div class="card card-default input-form">
        <div class="card-header text-center">Create New Account</div>
        <div class="card-body">
          <%= form_with(model: @user, url: register_path, local: true) do |f| %>
          <div class="form-horizontal col-md-9 mx-auto user-form">
            <div class="form-group">
              <%= f.label :name, class: "control-label" %>
              <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
              <% if @user.errors[:name].present? %>
                <span class="form-text"><b><%= @user.errors[:name][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :email, class: "control-label" %>
              <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
              <% if @user.errors[:email].present? %>
                <span class="form-text"><b><%= @user.errors[:email][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :username, class: "control-label" %>
              <%= f.text_field :username, class: "form-control", placeholder: "UserName" %>
              <% if @user.errors[:username].present? %>
                <span class="form-text"><b><%= @user.errors[:username][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :password, class: "control-label" %>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
              <% if @user.errors[:password].present? %>
                <span class="form-text"><b><%= @user.errors[:password][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <div><%= f.label :gender, class: "control-label" %></div>
              <div class="form-check form-check-inline">
                <%= f.radio_button :gender, 'm', class: 'form-check-input' %>
                <%= f.label :gender, 'Male', class: "form-check-label", value: 'm' %>
              </div>
              <div class="form-check form-check-inline">
                <%= f.radio_button :gender, 'f', class: 'form-check-input' %>
                <%= f.label :gender, 'Female', class: "form-check-label", value: 'f' %>
              </div>
              <% if @user.errors[:gender].present? %>
                <span class="form-text"><b><%= @user.errors[:gender][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.label :address, class: "control-label" %>
              <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
              <% if @user.errors[:address].present? %>
                <span class="form-text"><b><%= @user.errors[:address][0] %></b></span>
              <% end %>
            </div>
            <div class="form-group col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Register</button>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container main-content position-relative">
  <%= render 'layouts/back_btn' %>
  <div class="col-md-6 mx-auto align-middle content">
    <%= render 'layouts/flash_msg' %>
    <div class="card card-default">
      <div class="card-header text-center">User Profile</div>
      <div class="card-body col-md-10 mx-auto">
        <div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="d-flex w-100 justify-content-between">
                <span class="mb-2">Name : </span>
                <span><%= current_user.name %></span>
              </div>
            </li>
            <li class="list-group-item">
              <div class="d-flex w-100 justify-content-between">
                <span class="mb-2">Username : </span>
                <span><%= current_user.username %></span>
              </div>
            </li>
            <li class="list-group-item">
              <div class="d-flex w-100 justify-content-between">
                <span class="mb-2">Email : </span>
                <span><%= current_user.email %></span>
              </div>
            </li>
            <li class="list-group-item">
              <div class="d-flex w-100 justify-content-between">
                <span class="mb-2">Gender : </span>
                <span><%= current_user.gender == 'm' ? 'Male' : 'Female' %></span>
              </div>
            </li>
            <li class="list-group-item">
              <div class="d-flex w-100 justify-content-between">
                <span class="mb-2">Address : </span>
                <span><%= current_user.address %></span>
              </div>
            </li>
          </ul>
        </div>
        <div class="profile-btns">
          <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-confirm-modal">Delete</a>
          <%= link_to 'Edit Profile', profile_edit_path, class: 'btn btn-light float-right edit-profile-btn' %>
          <%= link_to 'Change Password', password_edit_path, class: 'btn btn-light float-right' %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/confirm_delete', msg: 'Please confirm your account will be deleted.', delete_path: profile_delete_path, btn_txt: 'Delete My Account' %>
</div>